// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
  | prismic.CustomTypeModelFetchCustomTypeLevel1
  | prismic.CustomTypeModelFetchCustomTypeLevel2
  | prismic.CustomTypeModelFetchGroupLevel1
  | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
    ? prismic.GroupField<
      PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
    >
    : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
  | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
  | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | PurchaseButtonSlice
  | MarqueeSlice
  | SwitchPlaygroundSlice
  | ColorChangerSlice
  | BentoBoxSlice
  | HeroSlice
  | ComparisonTableSlice
  | TestimonialsSlice
  | TechnicalSpecsSlice
  | AmbientBackgroundSlice
  | ContentImageSplitSlice
  | TextRevealSlice
  | ClosingTransitionSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Name field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Price (cents) field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

/**
 * Content for Switch documents
 */
interface SwitchDocumentData {
  /**
   * Name field in *Switch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switch.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Hex Color field in *Switch*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: switch.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;
}

/**
 * Switch document from Prismic
 *
 * - **API ID**: `switch`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SwitchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SwitchDocumentData>, "switch", Lang>;

/**
 * Content for Keyboards documents
 */
interface KeyboardsDocumentData {
  /**
   * Slice Zone field in *Keyboards*
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; // Reusing homepage slices for now
  /**
   * Meta Title field in *Keyboards*
   */
  meta_title: prismic.KeyTextField;
  /**
   * Meta Description field in *Keyboards*
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Keyboards*
   */
  meta_image: prismic.ImageField<never>;
}
export type KeyboardsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<KeyboardsDocumentData>, "keyboards", Lang>;

/**
 * Content for Switches documents
 */
interface SwitchesDocumentData {
  /**
   * Slice Zone field in *Switches*
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Switches*
   */
  meta_title: prismic.KeyTextField;
  /**
   * Meta Description field in *Switches*
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Switches*
   */
  meta_image: prismic.ImageField<never>;
}
export type SwitchesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SwitchesDocumentData>, "switches", Lang>;

/**
 * Content for Configurator documents
 */
interface ConfiguratorDocumentData {
  /**
   * Slice Zone field in *Configurator*
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Configurator*
   */
  meta_title: prismic.KeyTextField;
  /**
   * Meta Description field in *Configurator*
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Configurator*
   */
  meta_image: prismic.ImageField<never>;
}
export type ConfiguratorDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ConfiguratorDocumentData>, "configurator", Lang>;

/**
 * Content for Technology documents
 */
interface TechnologyDocumentData {
  /**
   * Slice Zone field in *Technology*
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *Technology*
   */
  meta_title: prismic.KeyTextField;
  /**
   * Meta Description field in *Technology*
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Technology*
   */
  meta_image: prismic.ImageField<never>;
}
export type TechnologyDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<TechnologyDocumentData>, "technology", Lang>;

export type AllDocumentTypes =
  | HomepageDocument
  | KeyboardsDocument
  | SwitchesDocument
  | ConfiguratorDocument
  | TechnologyDocument
  | ProductDocument
  | SwitchDocument;

/**
 * Item in *BentoBox → Default → Primary → Items*
 */
export interface BentoBoxSliceDefaultPrimaryItemsItem {
  /**
   * Size field in *BentoBox → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Small" | "Medium" | "Large">;

  /**
   * Image field in *BentoBox → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *BentoBox → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *BentoBox → Default → Primary*
 */
export interface BentoBoxSliceDefaultPrimary {
  /**
   * Heading field in *BentoBox → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *BentoBox → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<BentoBoxSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for BentoBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BentoBox*
 */
type BentoBoxSliceVariation = BentoBoxSliceDefault;

/**
 * BentoBox Shared Slice
 *
 * - **API ID**: `bento_box`
 * - **Description**: BentoBox
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSlice = prismic.SharedSlice<
  "bento_box",
  BentoBoxSliceVariation
>;

/**
 * Primary content in *ColorChanger → Default → Primary*
 */
export interface ColorChangerSliceDefaultPrimary {
  /**
   * Heading field in *ColorChanger → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: color_changer.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ColorChanger → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: color_changer.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ColorChanger Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColorChangerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ColorChangerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ColorChanger*
 */
type ColorChangerSliceVariation = ColorChangerSliceDefault;

/**
 * ColorChanger Shared Slice
 *
 * - **API ID**: `color_changer`
 * - **Description**: ColorChanger
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColorChangerSlice = prismic.SharedSlice<
  "color_changer",
  ColorChangerSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Buy Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buy_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buy_button_text: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Marquee → Default → Primary → Phrases*
 */
export interface MarqueeSliceDefaultPrimaryPhrasesItem {
  /**
   * Text field in *Marquee → Default → Primary → Phrases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.phrases[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Marquee → Default → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
  /**
   * Direction field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  direction: prismic.SelectField<"Left" | "Right">;

  /**
   * Phrases field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.phrases[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  phrases: prismic.GroupField<Simplify<MarqueeSliceDefaultPrimaryPhrasesItem>>;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;

/**
 * Primary content in *PurchaseButton → Default → Primary*
 */
export interface PurchaseButtonSliceDefaultPrimary {
  /**
   * Eyebrow field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Button Text field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Body field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for PurchaseButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PurchaseButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PurchaseButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PurchaseButton*
 */
type PurchaseButtonSliceVariation = PurchaseButtonSliceDefault;

/**
 * PurchaseButton Shared Slice
 *
 * - **API ID**: `purchase_button`
 * - **Description**: PurchaseButton
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PurchaseButtonSlice = prismic.SharedSlice<
  "purchase_button",
  PurchaseButtonSliceVariation
>;

/**
 * Item in *SwitchPlayground → Default → Primary → Switches*
 */
export interface SwitchPlaygroundSliceDefaultPrimarySwitchesItem {
  /**
   * Switch field in *SwitchPlayground → Default → Primary → Switches*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playground.default.primary.switches[].switch
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  switch: ContentRelationshipFieldWithData<
    [{ id: "switch"; fields: ["name", "color"] }]
  >;
}

/**
 * Primary content in *SwitchPlayground → Default → Primary*
 */
export interface SwitchPlaygroundSliceDefaultPrimary {
  /**
   * Heading field in *SwitchPlayground → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playground.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *SwitchPlayground → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playground.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Switches field in *SwitchPlayground → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playground.default.primary.switches[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  switches: prismic.GroupField<
    Simplify<SwitchPlaygroundSliceDefaultPrimarySwitchesItem>
  >;
}

/**
 * Default variation for SwitchPlayground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SwitchPlaygroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SwitchPlaygroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SwitchPlayground*
 */
type SwitchPlaygroundSliceVariation = SwitchPlaygroundSliceDefault;

/**
 * SwitchPlayground Shared Slice
 *
 * - **API ID**: `switch_playground`
 * - **Description**: SwitchPlayground
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SwitchPlaygroundSlice = prismic.SharedSlice<
  "switch_playground",
  "switch_playground",
  SwitchPlaygroundSliceVariation
>;

/**
 * Item in *ComparisonTable → Default → Primary → Items*
 */
export interface ComparisonTableSliceDefaultPrimaryItemsItem {
  /**
   * Model Name field in *ComparisonTable → Default → Primary → Items*
   */
  model_name: prismic.KeyTextField;
  /**
   * Price field in *ComparisonTable → Default → Primary → Items*
   */
  price: prismic.KeyTextField;
  /**
   * Switch Type field in *ComparisonTable → Default → Primary → Items*
   */
  switch_type: prismic.KeyTextField;
  /**
   * Wireless field in *ComparisonTable → Default → Primary → Items*
   */
  wireless: prismic.BooleanField;
  /**
   * Hot Swappable field in *ComparisonTable → Default → Primary → Items*
   */
  hot_swappable: prismic.BooleanField;
  /**
   * Image field in *ComparisonTable → Default → Primary → Items*
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ComparisonTable → Default → Primary*
 */
export interface ComparisonTableSliceDefaultPrimary {
  /**
   * Heading field in *ComparisonTable → Default → Primary*
   */
  heading: prismic.RichTextField;
  /**
   * Items field in *ComparisonTable → Default → Primary*
   */
  items: prismic.GroupField<Simplify<ComparisonTableSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for ComparisonTable Slice
 */
export type ComparisonTableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComparisonTableSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ComparisonTable*
 */
type ComparisonTableSliceVariation = ComparisonTableSliceDefault;

/**
 * ComparisonTable Shared Slice
 */
export type ComparisonTableSlice = prismic.SharedSlice<
  "comparison_table",
  ComparisonTableSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Items*
 */
export interface TestimonialsSliceDefaultPrimaryItemsItem {
  /**
   * Quote field in *Testimonials → Default → Primary → Items*
   */
  quote: prismic.RichTextField;
  /**
   * Author field in *Testimonials → Default → Primary → Items*
   */
  author: prismic.KeyTextField;
  /**
   * Role field in *Testimonials → Default → Primary → Items*
   */
  role: prismic.KeyTextField;
  /**
   * Avatar field in *Testimonials → Default → Primary → Items*
   */
  avatar: prismic.ImageField<never>;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   */
  heading: prismic.RichTextField;
  /**
   * Items field in *Testimonials → Default → Primary*
   */
  items: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Testimonials Slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Item in *TechnicalSpecs → Default → Primary → Specs*
 */
export interface TechnicalSpecsSliceDefaultPrimarySpecsItem {
  /**
   * Label field in *TechnicalSpecs → Default → Primary → Specs*
   */
  label: prismic.KeyTextField;
  /**
   * Value field in *TechnicalSpecs → Default → Primary → Specs*
   */
  value: prismic.KeyTextField;
}

/**
 * Primary content in *TechnicalSpecs → Default → Primary*
 */
export interface TechnicalSpecsSliceDefaultPrimary {
  /**
   * Heading field in *TechnicalSpecs → Default → Primary*
   */
  heading: prismic.RichTextField;
  /**
   * Description field in *TechnicalSpecs → Default → Primary*
   */
  description: prismic.RichTextField;
  /**
   * Specs field in *TechnicalSpecs → Default → Primary*
   */
  specs: prismic.GroupField<Simplify<TechnicalSpecsSliceDefaultPrimarySpecsItem>>;
}

/**
 * Default variation for TechnicalSpecs Slice
 */
export type TechnicalSpecsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TechnicalSpecsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TechnicalSpecs*
 */
type TechnicalSpecsSliceVariation = TechnicalSpecsSliceDefault;

/**
 * TechnicalSpecs Shared Slice
 */
export type TechnicalSpecsSlice = prismic.SharedSlice<
  "technical_specs",
  TechnicalSpecsSliceDefault,
  TechnicalSpecsSliceVariation
>;

/**
 * Primary content in *AmbientBackground → Default → Primary*
 */
export interface AmbientBackgroundSliceDefaultPrimary {
  /**
   * Overlay Heading field in *AmbientBackground → Default → Primary*
   */
  heading: prismic.RichTextField;
  /**
   * Visual Style field in *AmbientBackground → Default → Primary*
   */
  style: prismic.SelectField<"Stars" | "Grid" | "Noise">;
}

/**
 * Default variation for AmbientBackground Slice
 */
export type AmbientBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AmbientBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AmbientBackground*
 */
type AmbientBackgroundSliceVariation = AmbientBackgroundSliceDefault;

/**
 * AmbientBackground Shared Slice
 */
export type AmbientBackgroundSlice = prismic.SharedSlice<
  "ambient_background",
  AmbientBackgroundSliceVariation
>;

/**
 * Primary content in *ContentImageSplit → Default → Primary*
 */
export interface ContentImageSplitSliceDefaultPrimary {
  /**
   * Heading field in *ContentImageSplit → Default → Primary*
   */
  heading: prismic.RichTextField;
  /**
   * Body field in *ContentImageSplit → Default → Primary*
   */
  body: prismic.RichTextField;
  /**
   * Image field in *ContentImageSplit → Default → Primary*
   */
  image: prismic.ImageField<never>;
  /**
   * Image Position field in *ContentImageSplit → Default → Primary*
   */
  image_position: prismic.SelectField<"Left" | "Right">;
}

/**
 * Default variation for ContentImageSplit Slice
 */
export type ContentImageSplitSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentImageSplitSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentImageSplit*
 */
type ContentImageSplitSliceVariation = ContentImageSplitSliceDefault;

/**
 * ContentImageSplit Shared Slice
 */
export type ContentImageSplitSlice = prismic.SharedSlice<
  "content_image_split",
  ContentImageSplitSliceVariation
>;

/**
 * Primary content in *TextReveal → Default → Primary*
 */
export interface TextRevealSliceDefaultPrimary {
  /**
   * Text field in *TextReveal → Default → Primary*
   */
  text: prismic.RichTextField;
  /**
   * Animation Style field in *TextReveal → Default → Primary*
   */
  style: prismic.SelectField<"Fade" | "Stagger" | "Rotate">;
}

/**
 * Default variation for TextReveal Slice
 */
export type TextRevealSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextRevealSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextReveal*
 */
type TextRevealSliceVariation = TextRevealSliceDefault;

/**
 * TextReveal Shared Slice
 */
export type TextRevealSlice = prismic.SharedSlice<
  "text_reveal",
  TextRevealSliceVariation
>;

/**
 * Primary content in *ClosingTransition → Default → Primary*
 */
export interface ClosingTransitionSliceDefaultPrimary {
  /**
   * Heading field in *ClosingTransition → Default → Primary*
   */
  heading: prismic.RichTextField;
  /**
   * CTA Text field in *ClosingTransition → Default → Primary*
   */
  cta_text: prismic.KeyTextField;
  /**
   * CTA Link field in *ClosingTransition → Default → Primary*
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for ClosingTransition Slice
 */
export type ClosingTransitionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClosingTransitionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ClosingTransition*
 */
type ClosingTransitionSliceVariation = ClosingTransitionSliceDefault;

/**
 * ClosingTransition Shared Slice
 */
export type ClosingTransitionSlice = prismic.SharedSlice<
  "closing_transition",
  ClosingTransitionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      SwitchDocument,
      SwitchDocumentData,
      KeyboardsDocument,
      KeyboardsDocumentData,
      SwitchesDocument,
      SwitchesDocumentData,
      ConfiguratorDocument,
      ConfiguratorDocumentData,
      TechnologyDocument,
      TechnologyDocumentData,
      AllDocumentTypes,
      BentoBoxSlice,
      BentoBoxSliceDefaultPrimaryItemsItem,
      BentoBoxSliceDefaultPrimary,
      BentoBoxSliceVariation,
      BentoBoxSliceDefault,
      ColorChangerSlice,
      ColorChangerSliceDefaultPrimary,
      ColorChangerSliceVariation,
      ColorChangerSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MarqueeSlice,
      MarqueeSliceDefaultPrimaryPhrasesItem,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceVariation,
      MarqueeSliceDefault,
      PurchaseButtonSlice,
      PurchaseButtonSliceDefaultPrimary,
      PurchaseButtonSliceVariation,
      PurchaseButtonSliceDefault,
      SwitchPlaygroundSlice,
      SwitchPlaygroundSliceDefaultPrimarySwitchesItem,
      SwitchPlaygroundSliceDefaultPrimary,
      SwitchPlaygroundSliceVariation,
      SwitchPlaygroundSliceDefault,
      ComparisonTableSlice,
      ComparisonTableSliceDefaultPrimaryItemsItem,
      ComparisonTableSliceDefaultPrimary,
      ComparisonTableSliceVariation,
      ComparisonTableSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryItemsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TechnicalSpecsSlice,
      TechnicalSpecsSliceDefaultPrimarySpecsItem,
      TechnicalSpecsSliceDefaultPrimary,
      TechnicalSpecsSliceVariation,

      TechnicalSpecsSliceDefault,
      AmbientBackgroundSlice,
      AmbientBackgroundSliceDefaultPrimary,
      AmbientBackgroundSliceVariation,
      AmbientBackgroundSliceDefault,
      ContentImageSplitSlice,
      ContentImageSplitSliceDefaultPrimary,
      ContentImageSplitSliceVariation,
      ContentImageSplitSliceDefault,
      TextRevealSlice,
      TextRevealSliceDefaultPrimary,
      TextRevealSliceVariation,

      TextRevealSliceDefault,
      ClosingTransitionSlice,
      ClosingTransitionSliceDefaultPrimary,
      ClosingTransitionSliceVariation,
      ClosingTransitionSliceDefault,
    };
  }
}
