// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  color_changer: dynamic(() => import("./ColorChanger")),
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
  purchase_button: dynamic(() => import("./PurchaseButton")),
  comparison_table: dynamic(() => import("./ComparisonTable")),
  switch_playground: dynamic(() => import("./SwitchPlayground")),
  testimonials: dynamic(() => import("./Testimonials")),
  technical_specs: dynamic(() => import("./TechnicalSpecs")),
  ambient_background: dynamic(() => import("./AmbientBackground")),
  content_image_split: dynamic(() => import("./ContentImageSplit")),
  text_reveal: dynamic(() => import("./TextReveal")),
  closing_transition: dynamic(() => import("./ClosingTransition")),
};
